### ISSUE TITLE
[do not close] Sphinx porting TASK 1 work plan 

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos-core-wiki#31]
Legend: FR = Francesco, MW = Marcin 
- [x] propose and decide the structure of the new website
- [x] copy the content of the current kokkos wiki (keeping file formats as they are, i.e. md, etc) to the new thing
- [x] decide where in the Kokkos organization this new website has to go (kokkos team)
- [x] set up CI with constraints and autodeploy
- [ ] transition API from markdown to rst following the style Francesco/Nick have prototyped

**Comment by fnrizzi** [comment]
superseeded by #120
