### ISSUE TITLE
all bultin reducers pages must use `.. cppkokkos:class` to avoid duplication warnings

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos-core-wiki#397]
@antoinemeyer5 and I found out that all the warnings related to the *builtin reducers* currently showing when building the doc are due to the fact that those pages do not use `.. cppkokkos:class` to define the class, they just list things in separate sections. 
So what happens is that sphinx does not have a way to "scope" those things within each class and thinks all functions (for example the method `join`) are duplicate. To avoid this, we need to make sure those pages use the class from sphinx explicitly. 
This issue is to track the progress for this: 

- [x] BAnd.rst : see #398 
- [ ] BOr.rst : see #401 
- [x] LAnd.rst : see #402
- [x] LOr.rst : see #404
- [x] Max.rst : see #405
- [x] MaxLoc.rst : see #406
- [x] Min.rst : see #407
- [x] MinLoc.rst : see #408
- [x] MinMax.rst : see #409
- [x] MinMaxLoc.rst : see #410
- [x] MinMaxLocScalar.rst : see #411
- [x] MinMaxScalar.rst : see #412
- [x] Prod.rst : see #413
- [x] Sum.rst : see #414

related to #378

**Comment by antoinemeyer5** [comment]
@fnrizzi
Need clarification for #411 and #412.
Otherwise ready for review.

**Comment by cz4rs** [comment]
PRs look good overall. 
`.. rubric:: Assignment Operator` might be redundant, but I don't think we should change it when fixing warnings.
